media:
  input: src/assets/images
  output: dist/images
content:
  - name: Blog
    label: Blog
    type: collection
    path: src/content/post
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: tag, label: Tag, type: select, options: {values: [ Tech, News, Sports ]} }
      - { name: body, label: Body, type: rich-text }
  - label: Home page
    path: src/index.njk
    name: homepage
    type: file
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - name: features
        label: Features
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: title, label: Title, type: string }
              - { name: description, label: Description, type: string }
              - { name: icon, label: Icon, type: string }
              - { name: pro, label: Pro, type: boolean }
              - { name: soon, label: Soon, type: boolean }